services:
  mongodb-service:
    container_name: mongodb-service
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - shared_network
    dns:
      - 8.8.8.8
    restart: "unless-stopped"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '0.5'

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./OTEL/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.3'

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - shared_network
    depends_on:
      - prometheus
      # - loki
      # - tempo
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'

  loki:
    container_name: loki
    # image: grafana/loki:3.3.2
    image: grafana/loki:3.5.0

    ports:
      - 3100:3100
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - loki_data:/tmp
    restart: unless-stopped
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - 4317:4317  # OTLP gRPC endpoint
      - 3200:3200  # HTTP endpoint (optional)
    volumes:
      - ./LGTM/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    networks:
      - shared_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./LGTM/prometheus/:/etc/prometheus/
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=exemplar-storage'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.1'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password:-#password123sdJwnwlk}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-password123} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '1.0'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.2'

  mcpgateway:
    container_name: mcp-gateway
    restart: unless-stopped
    networks:
      - shared_network
    ports:
      - 8080:8080
    image: docker/mcp-gateway
    command:
      - --servers=duckduckgo,fetch,memory
      - --transport=streaming
      - --port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    models:
      - llm

models:
  llm:
    model: ai/smollm2
    context_size: 1024
    # extra_hosts:
    # - "model-runner.docker.internal:host-gateway"

volumes:
  mongodb_data:
    name: mongodb_data
    external: true

  grafana_data:
    name: grafana_data
    external: true

  prom_data:
    name: prom_data
    external: true

  loki_data:
    name: loki_data
    external: true

  tempo_data:
    name: tempo_data
    external: true

  sqlserver_data:
    name: sqlserver_data
    external: true

  portainer_data:
    name: portainer_data
    external: true

networks:
  shared_network:
    external: true
