receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'my-app'
          metrics_path: '/api/v1/metrics'
          scheme: http
          static_configs:
            - targets: ['bot-api-service:8081']

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: otel-collector:9090


  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
